<?php
/**
 * Class Livelog
 * Included in the client code. Instances of this are created in that client code, then have their postToServer() method called. 
 */
class LiveLog{
  public $filename;
  public $sessionID;
  
  /**
   * Constructor
   * @params
   *	$filename, the name of the file upon which logging is being performed. 
   *	$sessionID, the unique identifier for the users session, generated by front_end/new_session.php
   */
  function __construct($filename, $sessionID){
    $this->filename = $filename;
    $this->sessionID = $sessionID;
  }

  public function postToServer($var){
	  //where are we posting to?
	  $url = 'http://localhost/LiveLog/front_end/LiveLogCatch.php';

	  //making an array with the filename and the data to be logged as the elements
	  $arr = array('filename'=>$this->filename, 'logData'=>$var); 

	  //the data is a string to be used in the POST request. It consists of a json array containing the filename and variable to be logged,
	  //as well as the session id. 
	  $data = 'data='.json_encode($arr)."&sessionID=".$this->sessionID;

	  //TODO: add log index variable, so we can have multiple logging events 

	  //open connection
	  $ch = curl_init();

	  //CURL is used to post or get data from/to http
	  //set the url, number of POST vars, POST data
	  curl_setopt($ch,CURLOPT_URL,$url);//url to post to
	  curl_setopt($ch,CURLOPT_POST,count($data));//using the = delimeter, this knows we have to variables to post (how many variables)
	  curl_setopt($ch,CURLOPT_POSTFIELDS,$data); //this is the actual data to be passed

	  //execute post
	  $result = curl_exec($ch);

	  //close connection
	  curl_close($ch);
  } // end postLog

} // end LiveLog class def

?>
